name: "hello to develop branch"
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Hello to pull request"
              run: echo "Hello to pull request"